title: Harrison Cramer # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a seasoned journalist and software engineer building tools and applications for reporters in Washington.
  <br><br>
  At National Journal, I cover national security issues, at the State Department, the Pentagon, and in the halls of Congress. I'm also a self-taught software engineer. As someone with a foot in both worlds, I’ll bring a fresh set of skills to your team and we'll build amazing software.
  <br><br>
  <a href="https://www.linkedin.com/in/harrison-cramer/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-172772578-2 # your Google Analytics tracking ID here
